name: Yawsnd-Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install meson ninja
        sudo apt update
        sudo apt install python3 libusb-1.0-0-dev gobject-introspection valgrind libgirepository1.0-dev python3-gi libgusb-dev libmosquitto-dev
    - name: Build
      run: |
        meson --buildtype=plain . ./build
        ninja -C ./build
      env:
        CC: gcc
    - name: Tests
      run: meson test -C build/ -v
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt
